### PR TITLE
Fixed error while trying to assert remotePolicy during revoke operation

### PR DESCRIPTION
**Pull request by mikeadityas**
When trying to revoke a credential created using the policy-based method, Vault always throws this error:
`failed to revoke entry: resp: (*logical.Response)(nil) err: secret is missing inline_policies internal data`  
This is caused by a wrong value assertion during getting the `inlinePolicy` value from the Secret storage.  
This PR substituted the assertion with JSON Marshalling and Unmarshalling to fix the assertion error.

### CODE REVIEW

**Comment by tyrannosaurus-becks** [comment]
Hi! Thanks for providing this PR.

I've looked at it, and what I'm seeing is that the code in its present state has test coverage where if we run a remote policy through it in the expected format, it succeeds. It appears to me that this PR merely gives more information if it fails.

Could you provide us with steps to reproduce what you're seeing? I'm particularly interested in what you'll get if you run:
```
$ vault read alicloud/role/$YOUR_ROLE_NAME
```

**Comment by mikeadityas** [comment]
Hi Beck,

Thank you for reaching back.

The steps to reproduce the issue are as follow:
1. Enable the secrets engine
```vault secrets enable alicloud```

2. Create this custom policy in the AlibabaCloud console:
```
{
    "Statement": [
        {
            "Action": [
                "ram:CreateAccessKey",
                "ram:DeleteAccessKey",
                "ram:CreatePolicy",
                "ram:DeletePolicy",
                "ram:AttachPolicyToUser",
                "ram:DetachPolicyFromUser",
                "ram:CreateUser",
                "ram:DeleteUser"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ],
    "Version": "1"
}
```

3. Create a User for Vault with the previous custom policy and get the access keypair

4. Upload the access keypair to Vault configuration
```
vault write alicloud/config \
            access_key=<ALICLOUD_ACCESS_KEY_ID> \
            secret_key=<ALICLOUD_SECRET_ACCESS_KEY>
```

5. Configure a Vault role
```
vault write alicloud/role/myrole \
    remote_policies='name:AliyunECSReadOnlyAccess,type:System' \
    remote_policies='name:AliyunRDSReadOnlyAccess,type:System' \
    inline_policies=-<<EOF
[
    {
      "Statement": [
        {
          "Action": "rds:Describe*",
          "Effect": "Allow",
          "Resource": "*"
        }
      ],
      "Version": "1"
    }
]
EOF
```
I've also tested without specifying the `inline_policies` and it still returns the same error
```
vault write alicloud/role/myrole2 \
    remote_policies='name:AliyunECSReadOnlyAccess,type:System' \
    remote_policies='name:AliyunRDSReadOnlyAccess,type:System'
```

6. Retrieve a dynamic credential for this role
```
vault write alicloud/creds/myrole
```

7. Try to revoke the created lease from the UI and it does nothing and returned the error I mentioned earlier in the network tab in the developer console. The dynamic credential key pair is revoked though, but the dynamically created user is not properly deleted (which is not expected).

 And for this
```$ vault read alicloud/role/$YOUR_ROLE_NAME```
the result is:

```
$ vault read alicloud/role/myrole
Key                Value
---                -----
inline_policies    [map[hash:59b7ee94a1d2254d711de151661f75d9 policy_document:map[Statement:[map[Effect:Allow Resource:* Action:rds:Describe*]] Version:1]]]
max_ttl            0s
remote_policies    [map[name:AliyunECSReadOnlyAccess type:System] map[type:System name:AliyunRDSReadOnlyAccess]]
role_arn           n/a
ttl                0s
```

```
$ vault read alicloud/role/myrole2 
Key                Value
---                -----
inline_policies    <nil>
max_ttl            0s
remote_policies    [map[name:AliyunECSReadOnlyAccess type:System] map[name:AliyunRDSReadOnlyAccess type:System]]
role_arn           n/a
ttl                0s

```

**Comment by tyrannosaurus-becks** [comment]
Hi, 

Ah! Thank you for that reproduction. I am able to see the error you're talking about now. I get it on the main branch. Thank you so much for spotting it and pointing it out!

When I pull and try your branch, I get this when I revoke a lease:
```
2020-01-27T16:14:21.190-0800 [ERROR] expiration: failed to revoke lease: lease_id=alicloud/creds/myrole/4feQ9dWYeTx7uo4XcIK0LiLi error="failed to revoke entry: resp: (*logical.Response)(nil) err: malformed remote_policies internal data"
```

I tried a couple of different approaches and found that this one works:
```
func getRemotePolicies(internalData map[string]interface{}, key string) ([]*remotePolicy, error) {
	valuesRaw, ok := internalData[key]
	if !ok {
		return nil, fmt.Errorf("secret is missing %s internal data", key)
	}
	if valuesRaw == nil {
		// This will happen if this policy type simply wasn't used.
		return nil, nil
	}
	policiesIfc, ok := valuesRaw.([]interface{})
	if !ok {
		return nil, fmt.Errorf("secret is missing %s internal data: %T", key, internalData)
	}
	policies := make([]*remotePolicy, len(policiesIfc))
	for i, policyIfc := range policiesIfc {
		policyMap := policyIfc.(map[string]interface{})
		policies[i] = &remotePolicy{
			Name: policyMap["name"].(string),
			Type: policyMap["type"].(string),
		}
	}
	return policies, nil
}
```
Let me know if you see a better way to get it working.

**Comment by mikeadityas** [comment]
Hi,

For this error
`2020-01-27T16:14:21.190-0800 [ERROR] expiration: failed to revoke lease: lease_id=alicloud/creds/myrole/4feQ9dWYeTx7uo4XcIK0LiLi error="failed to revoke entry: resp: (*logical.Response)(nil) err: malformed remote_policies internal data"`
I think it's because I forgot to check for nil value.

That's a good approach, but wouldn't it be simpler to use JSON encoding and decoding? By using that, whenever there is a change in the `remotePolicy` struct, we don't need to update this function as it'll automatically adapt to the change, hence less code to maintain.
```
func getRemotePolicies(internalData map[string]interface{}, key string) ([]*remotePolicy, error) {
	valuesRaw, ok := internalData[key]
	if !ok {
		return nil, fmt.Errorf("secret is missing %s internal data", key)
	}

	if valuesRaw == nil {
		// This will happen if this policy type simply wasn't used.
		return nil, nil
	}

	valuesJSON, err := jsonutil.EncodeJSON(valuesRaw)
	if err != nil {
		return nil, fmt.Errorf("secret is missing %s internal data", key)
	}

	policies := []*remotePolicy{}
	if err := jsonutil.DecodeJSON(valuesJSON, &policies); err != nil {
		return nil, fmt.Errorf("failed to unmarshal %s internal data as remotePolicy", key)
	}
	return policies, nil
}
```
What do you think?

**Comment by mikeadityas** [comment]
> Hi! Actually, I re-tested it and it's working. blush It was probably an incorrect test on my part.
> 
> Thank you for spotting and fixing this! Looks great.

Hi! You're welcome! :+1: 

Btw, when will this patch be reflected in the Vault release?

**Comment by tyrannosaurus-becks** [comment]
Middle of March at the very latest, though it may go out as soon as late February.

**Comment by icecoffee531** [comment]
The error 'malformed remote_policies internal data' still exists, and the code checking for nil values has not been merged into the master branch. @mikeadityas

**Pull request merged**
